<h2>This is the Student Page</h2>

<style>
    div#insertrecord
    {
        color: #FFF;
        font-size: 24px;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
</style>

<div id="welcome">
Welcome, <strong><?= $this->name->first_name; ?> <?= $this->name->last_name; ?></strong>
<p>Your current program is <strong><?= $this->roledesc->description; ?></strong></p>
</div>

<button type="button">Upload Artifacts</button>   <button type="button">Manage Portfolio</button>

<hr>


<div id="uploads">
	<strong>Recent Uploads</strong>
	<dl>
		<?= $this->partialLoop('partials/uploadRow.phtml', $this->uploads);?>
	</dl>
</div>

<div id="linked">
	<strong>Recent Linked Artifacts</strong>
	<dl>
		<?= $this->partialLoop('partials/linkedArtifactRow.phtml', $this->links);?>
	</dl>
</div>
<div id="submissions">
	<strong>Recent Submissions</strong>
	<p>
		<?= $this->partialLoop('partials/submissionRow.phtml', $this->submit);?>
	</p>
</div>
<div id="feedback">
	<strong>Recent Feedback</strong>
	<p>
		<?= $this->partialLoop('partials/evaluatedRow.phtml', $this->evaluated);?>
	</p>
</div>

