
<h2>Insert New Artifact</h2>
<?= $this->form?>
<!-- <form id="frm" method="POST">

	<label for="artifact_title">Title:</label>
	<input type="text" title="artifact_title" id="artifact_title" value="" />
	
	<label for="title">Description:</label>
	<input type="text" title="description" id="description" value="" />
	
	<label for="title">Filename:</label>
	<input type="text" title="media_extention" id="media_extention" value="" />

	<input type="submit" name="btsubmit" id="btsubmit" value="submit" />
</form> -->
<!--<?= $this->partial('studentartifact/artifactForm.phtml', array(
			'artifact_title' => '',
			'description' => '',
			'media_extention' => ''))?>-->

<h2>Artifacts</h2>
<dl>
<?= $this->partialLoop('studentartifact/userRow.phtml', $this->user);?>
</dl>

