
<h2>Insert New Artifact</h2>

<?= $this->form;?>

<?php echo "<table id=\"student_artifact_table\" class =\"student_artifact_table\" cellspacing=\"0\">";?>
<?php echo "<tr>";
          echo "<th>Artifact Title</th>";
          echo "<th>Memo</th>";
          echo "</tr>";
        ?>


<h2>Artifacts</h2>
<dl>
<?= $this->partialLoop('studentartifact/userRow.phtml', $this->user);?>
<?php echo "</table>" ?>
</dl>
